### ISSUE TITLE
[Iteracion 0] Elaboración de requisitos y planificación de iteraciones

### ISSUE THREAD

**Issue by asungomez** [asungomez/EstimacionDemograficaPFG#1]
# Descripción

Como inicio de un proyecto de software, es fundamental adquirir conocimientos sobre el dominio del problema, las herramientas existentes actualmente, y las necesidades a cubrir con el desarrollo de la herramienta. En esta iteración, se pretende describir y delimitar el alcance del proyecto, y crear un primer borrador de requisitos generales, que se irá refinando a lo largo de las iteraciones.

# Tareas a realizar

- [x] Investigar los servicios externos de clasificación de textos y su uso (#2)
- [x] Buscar herramientas similares al proyecto a desarrollar, indicando sus puntos fuertes y débiles (#3)
- [x] Elaborar el flujo de los casos de uso principales (#4)
- [x] Redactar el primer borrador de requisitos (#5)
- [x] Planificar las iteraciones (#6)
